trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'vinutnaserviceconn'  # Azure service connection name
  resourceGroup: 'myDataPlatformRG'
  devFactoryName: 'vinutnadfdev'
  prodFactoryName: 'vinutnadfprod'
  location: 'Japan East'

stages:
  - stage: DeployToDev
    displayName: 'Deploy to Development ADF'
    jobs:
      - job: DeployDev
        displayName: 'Deploy ADF Pipeline to Dev'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az datafactory pipeline create \
                  --factory-name $(devFactoryName) \
                  --resource-group $(resourceGroup) \
                  --name SamplePipeline \
                  --pipeline "@$(Build.SourcesDirectory)/Pipeline1.json"

  - stage: DeployToProd
    displayName: 'Deploy to Production ADF'
    dependsOn: DeployToDev
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        environment: vinutna-env  # approval happens here
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az datafactory pipeline create \
                        --factory-name $(prodFactoryName) \
                        --resource-group $(resourceGroup) \
                        --name SamplePipeline \
                        --pipeline "@$(Build.SourcesDirectory)/Pipeline1.json"
